apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: pvpod
      image: busybox:latest
      command: ["/bin/sh","-c","while true;do echo pod2 >> /root/out.txt; sleep 10; done;"]
      volumeMounts:
        - name: volume
          mountPath: /root/
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc1
        readOnly: false