services:
  redoc:
    image: docker.zhai.cm/redocly/redoc # 使用 Redoc 官方镜像
    container_name: redoc  # 容器名称
    ports:
        - "10086:9999"  # 将容器的 80 端口映射到主机的 8080 端口
    volumes:
        - ./docs:/usr/share/nginx/html/swagger  # 挂载 OpenAPI 文件
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 挂载 OpenAPI 文件
    environment:
        - SPEC_URL=swagger/a.yaml  # 指定 OpenAPI 文件的路径
        - PORT=9999  # 指定 OpenAPI 文件的路径
