version: '3'
services:
  bookstack:
    image: docker.zhai.cm/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - APP_URL=http://192.168.31.215:8989
      - APP_KEY=base64:f1p8OZZjzHk6Oa4Nkr5TF1lfQ5jyYznTT70Z909yUFM=
      - DB_HOST=bookstack_db
      - DB_USERNAME=bookstack
      - DB_PASSWORD=password
      - DB_DATABASE=bookstack
    volumes:
      - ./app/bookstack/data:/config
    ports:
      - "8989:80"
    depends_on:
      - bookstack_db

  bookstack_db:
    image: docker.zhai.cm/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password
    volumes:
      - ./app/mysql/data:/config

    #admin@admin.com password
    # docker run -it --rm --entrypoint /bin/bash docker.zhai.cm/linuxserver/bookstack:latest appke     获取appkey