apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
    - name: alpine
      image: 192.168.2.200:5000/alpine:1.0
      command: ["sleep", "infinity"]  # 保持容器不退出
  imagePullSecrets:
    - name: regcred
