apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: nginx-stateful
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stateful
  namespace: default
spec:
  serviceName: "nginx-headless"
  replicas: 1
  selector:
    matchLabels:
      app: nginx-stateful
  template:
    metadata:
      labels:
        app: nginx-stateful
    spec:
      containers:
        - name: nginx
          image: 192.168.2.200:5000/nginx:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
# k exec -it alpine-pod -- ping nginx-stateful-0.nginx-headless.default