# docker-compose配置参考：https://github.com/grafana/loki/blob/master/production/docker-compose.yaml
version: "3"

# 网桥loki -> 方便相互通讯
networks:
  loki:

services:
  # Loki日志系统
  loki:
    image: cr.laoyou.ip-ddns.com/grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./grafana_promtail_loki/loki:/etc/loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    networks:
      - loki

  # Loki官方支持的日志采集端
  promtail:
    image: cr.laoyou.ip-ddns.com/grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./grafana_promtail_loki/logs:/var/logs
      - ./grafana_promtail_loki/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-docker-config.yaml
    networks:
      - loki

  # 用于UI展示
  grafana:
    image: docker.zhai.cm/grafana/grafana:8.5.5
    container_name: prometheus-grafana
    restart: unless-stopped
    ports:
      - "3200:3000"
    volumes:
      - "./grafana_promtail_loki/grafana/grafana.ini:/etc/grafana/grafana.ini" # 邮箱配置
      - "./grafana_promtail_loki/grafana/grafana-storage:/var/lib/grafana"
    #      - "./prometheus/grafana/public:/usr/share/grafana/public" # 这里面可处理汉化包 可参考 https://github.com/WangHL0927/grafana-chinese
    #      - "./prometheus/grafana/conf:/usr/share/grafana/conf"
    #      - "./prometheus/grafana/log:/var/log/grafana"
    #      - "/etc/localtime:/etc/localtime"
    environment:
      GF_EXPLORE_ENABLED: "true"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
  #    GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app"
      GF_DEFAULT_INSTANCE_LANGUAGE: zh-Hans
    networks:
      - loki

  node-exporter:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/node-exporter:v1.3.1           # 原镜像`prom/node-exporter:v1.3.1`
    container_name: prometheus-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - loki
  prometheus:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/prometheus:v2.34.0             # 原镜像`prom/prometheus:v2.34.0`
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./grafana_promtail_loki/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    networks:
      - loki
    depends_on:
      - node-exporter
