apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonsetdemo
  namespace: default
spec:
  selector:
    matchLabels:
      app: daemonsetdemo
  template:
    metadata:
      labels:
        app: daemonsetdemo
    spec:
      containers:
        - name: daemonsetdemo
          image: 192.168.2.200:5000/daemonsetdemo:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: daemonsetdemosvc
  namespace: default
spec:
  type: NodePort
  selector:
    app: daemonsetdemo #和deploy中的标签要匹配上
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
      nodePort: 32002
